#!/bin/bash
echo "📥 REAL BRSET DATASET ACQUISITION"
echo "================================="
echo ""
echo "🔗 REQUIRED STEPS:"
echo "1. Go to: https://physionet.org/content/brazilian-ophthalmological/1.0.0/"
echo "2. Create PhysioNet account"
echo "3. Complete CITI training: 'Data or Specimens Only Research'"
echo "4. Sign Data Use Agreement (DUA)"
echo "5. Download dataset (will be ~2-3GB)"
echo ""
echo "📊 REAL BRSET CONTAINS:"
echo "  - 16,266 real retinal fundus images"
echo "  - labels.csv with real patient data"
echo "  - 13+ eye condition labels"
echo "  - Real clinical metadata"
echo ""
echo "⚠️  CRITICAL: No training until real data is downloaded!"
echo ""
echo "🔄 WHEN YOU HAVE REAL DATA:"
echo "1. Extract to: data/brset_real/"
echo "2. Run: bash integrate_real_data.sh"
